services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: order_aggregator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d order_aggregator"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    container_name: db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_ERLANG_COOKIE: "rabbitmq-cookie-string"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    image: app
    container_name: app
    build: .
    ports:
      - "8000:3000"
    environment:
      DB_HOST: postgres
      DB_NAME: order_aggregator
      DB_USER: postgres
      DB_PASSWORD: password
      RABBITMQ_URL: amqp://admin:password@rabbitmq:5672
      VENDOR_A_URL: http://vendor-a:3001
      VENDOR_B_URL: http://vendor-b:3002
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  worker:
    image: worker
    container_name: worker
    build: .
    command: ["npm", "run", "worker"]
    environment:
      DB_HOST: postgres
      DB_NAME: order_aggregator
      DB_USER: postgres
      DB_PASSWORD: password
      RABBITMQ_URL: amqp://admin:password@rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  vendor-a:
    image: vendor_a
    container_name: vendor_a
    build:
      context: .
      dockerfile: Dockerfile.vendor
    environment:
      PORT: 3001
      VENDOR_NAME: VendorA
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq

  vendor-b:
    image: vendor_b
    container_name: vendor_b
    build:
      context: .
      dockerfile: Dockerfile.vendor
    environment:
      PORT: 3002
      VENDOR_NAME: VendorB
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
